version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    registries:
      - github
    schedule:
      interval: 'daily'
    groups:
      github-actions-group:
        applies-to: version-updates
        patterns:
          - '*'
